### ISSUE TITLE
Rails 7.1 Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION

### ISSUE THREAD

**Issue by ron-shinall** [github/activerecord-trilogy-adapter#10]
I ran into this issue when trying to switch our Rails 7.1 application to Trilogy, but I have the same issue if I generate a new rails app and try to use Trilogy. The application is using MariaDB.

### Steps to reproduce

Generate a new Rails Edge app using MySQL:
```bash
❯ rails new MyApp --main -d mysql
```

Add the Trilogy gems to the Gemfile:
```ruby
# Gemfile

...
gem "trilogy"
gem "activerecord-trilogy-adapter"
...
```

Install the gems:
```bash
❯ bundle install
```

Set the adapter to trilogy in `database.yml`:
```yaml
# config/database.yml

...
  adapter: trilogy
...
```

Attempt to create the database:
```bash
❯ rails db:create
```

### Expected behavior
```bash
Created database 'my_app_development'
Created database 'my_app_test'
```
### Actual behavior
```bash
Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION
Couldn't create 'trilogy2_development' database. Please check your configuration.
rails aborted!
ActiveRecord::StatementInvalid: Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION


Caused by:
Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION

Tasks: TOP => db:create
(See full trace by running task with --trace)
```

Full trace:
```bash
❯ rails db:create --trace
** Invoke db:create (first_time)
** Invoke db:load_config (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:load_config
** Execute db:create
Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION
Couldn't create 'trilogy2_development' database. Please check your configuration.
rails aborted!
ActiveRecord::StatementInvalid: Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `initialize'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `new'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `new_client'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:210:in `connect'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:215:in `reconnect'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:596:in `block in reconnect!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:595:in `reconnect!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:705:in `verify!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `connect!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:910:in `block in with_raw_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:909:in `with_raw_connection'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:223:in `get_full_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:55:in `get_database_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/schema_cache.rb:145:in `database_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:784:in `database_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:612:in `check_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:660:in `block in new_connection'
<internal:kernel>:90:in `tap'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:659:in `new_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:703:in `checkout_new_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:682:in `try_to_checkout_new_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:643:in `acquire_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:344:in `checkout'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:178:in `connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:243:in `retrieve_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_handling.rb:287:in `retrieve_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_handling.rb:254:in `connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/mysql_database_tasks.rb:73:in `connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/mysql_database_tasks.rb:19:in `create'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:122:in `create'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:176:in `block in create_current'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:548:in `block (2 levels) in each_current_configuration'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:545:in `each'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:545:in `block in each_current_configuration'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:544:in `each'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:544:in `each_current_configuration'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:176:in `create_current'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/railties/databases.rake:46:in `block (2 levels) in <main>'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/command.rb:51:in `invoke'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands.rb:18:in `<main>'
/path_to/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/path_to/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'

Caused by:
Trilogy::Error: trilogy_connect - unable to connect to /tmp/mysql.sock: TRILOGY_PROTOCOL_VIOLATION
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `initialize'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `new'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:84:in `new_client'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:210:in `connect'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:215:in `reconnect'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:596:in `block in reconnect!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:595:in `reconnect!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:705:in `verify!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:712:in `connect!'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:910:in `block in with_raw_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activesupport/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:909:in `with_raw_connection'
/path_to/.rvm/gems/ruby-3.1.2/gems/activerecord-trilogy-adapter-2.1.0/lib/active_record/connection_adapters/trilogy_adapter.rb:223:in `get_full_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:55:in `get_database_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/schema_cache.rb:145:in `database_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb:784:in `database_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:612:in `check_version'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:660:in `block in new_connection'
<internal:kernel>:90:in `tap'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:659:in `new_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:703:in `checkout_new_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:682:in `try_to_checkout_new_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:643:in `acquire_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:344:in `checkout'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb:178:in `connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_adapters/abstract/connection_handler.rb:243:in `retrieve_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_handling.rb:287:in `retrieve_connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/connection_handling.rb:254:in `connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/mysql_database_tasks.rb:73:in `connection'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/mysql_database_tasks.rb:19:in `create'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:122:in `create'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:176:in `block in create_current'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:548:in `block (2 levels) in each_current_configuration'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:545:in `each'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:545:in `block in each_current_configuration'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:544:in `each'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:544:in `each_current_configuration'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/tasks/database_tasks.rb:176:in `create_current'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/activerecord/lib/active_record/railties/databases.rake:46:in `block (2 levels) in <main>'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands/rake/rake_command.rb:24:in `block (2 levels) in perform'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands/rake/rake_command.rb:24:in `block in perform'
/path_to/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_module.rb:59:in `with_application'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/command.rb:51:in `invoke'
/path_to/.rvm/gems/ruby-3.1.2/bundler/gems/rails-c41e2f1bca65/railties/lib/rails/commands.rb:18:in `<main>'
/path_to/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/path_to/.rvm/gems/ruby-3.1.2/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:create
```

### System configuration
**Rails version**: 7.1.0.alpha

**Ruby version**:  ruby-3.1.2 [ arm64 ]

**MariaDB version**: 10.8.3-MariaDB Homebrew

**Comment by ron-shinall** [comment]
Yep, that fixed the issue. All of our tests pass when using the repo main branch! Any ETA on a release? Thanks so much!

**Comment by composerinteralia** [comment]
Version 2.1.2 released!
